### PR TITLE
Remember change type for each hunk.

### PR DESCRIPTION
**Pull request by paulhybryant**
I am writing a plugin that needs access to the change type of each hunk.

Thanks,

### CODE REVIEW

**Comment by paulhybryant** [comment]
Hi mhinz,

The change should be pretty straightforward to review. Can you take a quick look?

Thanks!

**Comment by mhinz** [comment]
Hi. Sorry for the late response, but I was on a long trip.

I'll review this change later today.

**Comment by paulhybryant** [comment]
sure. Thank you for reviewing it.

**Comment by mhinz** [comment]
So, the patch itself looks alright, I just wonder if it's what you really want. :)

You basically add one type to a hunk, but a hunk can have several types, so the last set type will "win".

**Comment by paulhybryant** [comment]
I am basically trying to add another thing like a gutter, but shows how many hunks are there in this file, where is it, and also indicate which hunk I am currently at. It is like an indicator with overview of hunks.

Because there are limited spaces, two hunks with different types can overlap so I will just pick one of them.

Basically something look like this:
example

**Comment by mhinz** [comment]
Sorry, but somehow I can't see the value in it, especially because of the thing I noted above.

You want a one-to-many relationship and give a type to the sign, but the sign is indicating a hunk which has several types. This approach seems a bit misleading, IMHO.

**Pull request closed without merging**
