### PR TITLE
allow `p4 diff` command to actually work on Windows (prevent missing env command error)

### PR DESCRIPTION
**Pull request by AaronM04**
I fixed this for Windows. I could not test on other platforms. Please let me know if changes are needed to make this work everywhere. Thanks!

### CODE REVIEW

**Comment by mhinz** [comment]
I think the `P4DIFF=diff` was originally used because the internal diff routine had no notion of a unified diff.

Shouldn't it be `-du0` (lowercase `u`), though? https://www.perforce.com/perforce/r18.1/manuals/cmdref/Content/CmdRef/p4_diff.html

Do you happen to know any freely accessible Perforce repo that I could use for testing?

**Comment by AaronM04** [comment]
> Shouldn't it be -du0 (lowercase u), though? 

I don't believe so. I have used -du on the command line many times.

> Do you happen to know any freely accessible Perforce repo that I could use for testing?

No, but I'll look around for one.

On July 24, 2018 4:55:23 PM PDT, Marco Hinz <notifications@github.com> wrote:
>I think the `P4DIFF=diff` was originally used because the internal diff
>routine had no notion of a unified diff.
>
>Shouldn't it be `-du0` (lowercase `u`), though?
>https://www.perforce.com/perforce/r18.1/manuals/cmdref/Content/CmdRef/p4_diff.html
>
>Do you happen to know any freely accessible Perforce repo that I could
>use for testing?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mhinz/vim-signify/pull/263#issuecomment-407588849

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AaronM04** [comment]
After looking again at the code and the docs, I think maybe there is undocumented support for capital `U`. It definitely works on my system with vim-signify.

**Comment by AaronM04** [comment]
As for a public Perforce repo, I didn't test this since I'm on mobile, but this looks promising: https://swarm.workshop.perforce.com/view/public/tutorial.html?v=14

**Pull request merged**
